config/routes.rb
Doggifs::Application.routes.draw do
  resources :gifs

end

app/models/gif.rb
class Gif < ActiveRecord::Base
  attr_accessible :favorite, :note, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifs }
    end
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
    @gif = Gif.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gif }
    end
  end

  # GET /gifs/new
  # GET /gifs/new.json
  def new
    @gif = Gif.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gif }
    end
  end

  # GET /gifs/1/edit
  def edit
    @gif = Gif.find(params[:id])
  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = Gif.new(params[:gif])

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: 'Gif was successfully created.' }
        format.json { render json: @gif, status: :created, location: @gif }
      else
        format.html { render action: "new" }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gifs/1
  # PUT /gifs/1.json
  def update
    @gif = Gif.find(params[:id])

    respond_to do |format|
      if @gif.update_attributes(params[:gif])
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif = Gif.find(params[:id])
    @gif.destroy

    respond_to do |format|
      format.html { redirect_to gifs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/views/gifs/_form.html.erb
<%= form_for(@gif) do |f| %>
  <% if @gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

      <ul>
      <% @gif.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :favorite %><br />
    <%= f.check_box :favorite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifs/edit.html.erb
<h1>Editing gif</h1>

<%= render 'form' %>

<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<h1>List of Pictures</h1>

<%= link_to "Add A New GIF", new_gif_url %>

<ul>
  <% @gifs.each do |gif| %>
    <li>
      <%= image_tag gif.url, :width => 200 %>
      <p>
        <%= link_to gif.note, gif_url(gif.id) %>
        <%= link_to "Edit", edit_gif_url(gif.id) %>
        <%= link_to "Delete", gif_url(gif.id), :method => :delete, :confirm => "Really?" %>
      </p>
    </li>
  <% end %>
</ul>

app/views/gifs/new.html.erb
<h1>New gif</h1>

<%= render 'form' %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @gif.url %>
</p>

<p>
  <b>Note:</b>
  <%= @gif.note %>
</p>

<p>
  <b>Favorite:</b>
  <%= @gif.favorite %>
</p>


<%= link_to 'Edit', edit_gif_path(@gif) %> |
<%= link_to 'Back', gifs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doggifs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>